#!/usr/bin/env bash
# Enable more locales on the Steam Deck
# This needs to be run after each OS update.

set -euo pipefail

if [[ ${EUID} -ne 0 ]]; then
    echo "This script must be run as root" >&2
    exit 1
fi

readonly LOCALES=(
    "ja_JP.UTF-8"
    "fr_FR.UTF-8"
    "en_DK.UTF-8"
)

# Disable the read-only filesystem
steamos-readonly disable

enable_readonly() {
    # Re-enable the read-only filesystem
    steamos-readonly enable
}
trap enable_readonly EXIT

# Initialize and setup the Pacman GPG keys
pacman-key --init
pacman-key --populate archlinux

# Reinstall glibc
pacman -S --noconfirm glibc

# Uncomment the locales in /etc/locale.gen
for locale in "${LOCALES[@]}"; do
    sed -i "s/^#\(${locale}\)/\1/" /etc/locale.gen
done

# Optional: delete the locales enabled through the System Settings
sed -i -e '/^# generated by KDE Plasma Region & Language KCM$/,$d' -e '/$^/d' /etc/locale.gen

# Re-generate the locales
locale-gen
